name: Deploy AWS lambda
on:
  push:
    paths:
      - "lambda/**"

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup python env
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      - name: Config AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: deploy lambda function
        run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code --function-name test-cicd --zip-file fileb://lambda.zip
