name: My first github actions workflow
on: [push]

jobs:
    testing_github:
        runs-on: ubuntu-latest
        steps:
            - name: hello
              run: echo "hellow from github actions"
            - name: display repo name
              run: echo "this workflow is runningin ${{github.repository}}"